# Generated by Django 5.1.2 on 2024-10-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eTrznica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisment',
            new_name='Advertisement',
        ),
    ]
