# Generated by Django 5.1.2 on 2024-10-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eTrznica', '0002_rename_advertisment_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
