# Generated by Django 5.1.2 on 2024-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsfull_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfull',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/news/'),
        ),
    ]
