# Generated by Django 5.1.2 on 2024-10-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsfull_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfull',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
