# Generated by Django 5.1.2 on 2024-10-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsfull_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfull',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
