# Generated by Django 5.1.2 on 2024-10-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsfull_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfull',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
